stages:
  train_model:
    cmd: python main.py 
    deps:
    - data/raw/train.csv
    - main.py
    - params.yaml
    params:
    - model.model_name
    - model.params.n_estimators
    - model.params.max_depth
    - model.params.random_state
    outs:
    - models/RandomForest.pkl
